config/routes.rb
Jumbo::Application.routes.draw do
  
  root :to => 'tourpackages#index'
  match 'tourpackages/:id/show' => 'tourpackages#show'
  
 
  
  get "pages/home"

  get "pages/about"

  get "pages/help"

  get "pages/contact"

  resources :tourpackages
  devise_for :travelagents
  devise_scope :travelagent do
   match '/travelagents' => 'travelagents#index'
end

end

app/models/tourpackage.rb
# == Schema Information
#
# Table name: tourpackages
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  desc          :text
#  iternary      :text
#  price         :integer
#  countries     :text
#  numdays       :integer
#  landmarks     :text
#  maxseats      :integer
#  minseats      :integer
#  incairfare    :boolean
#  incbreakfast  :boolean
#  inclunch      :boolean
#  incsnacks     :boolean
#  incdinner     :boolean
#  sourcecity    :string(255)
#  sourceaddress :text
#  active        :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Tourpackage < ActiveRecord::Base
  attr_accessible :active, :arrtime, :countries, :deptime, :desc, :enddate, :incairfare, :incbreakfast, :incdinner, :inclunch, :incsnacks, :iternary, :landmarks, :maxseats, :minseats, :numdays, :price, :sourceaddress, :sourcecity, :startdate, :title
  
belongs_to :travelagent

validates :title, :presence => "true"

  
end

app/models/travelagent.rb
# == Schema Information
#
# Table name: travelagents
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(128)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Travelagent < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :tourpackages, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/tourpackages_controller.rb
class TourpackagesController < ApplicationController
  
  before_filter :authenticate_travelagent!, :except => [:index,:show]
  
  def index
    @tourpackage = Tourpackage.all
  end

  def new
    @tourpackage = current_travelagent.tourpackages.new(params[:tourpackage])
  end

  def show
    
    if Tourpackage.find(params[:id])
      @tourpackage = Tourpackage.find(params[:id])
    else
      @tourpackage = ""
    end

  end

  def create
     @tourpackage = current_travelagent.tourpackages.new(params[:tourpackage])
      if @tourpackage.save
        redirect_to root_path, :notice => "Success, Tour offer Created!"
      else
        redirect_to new_tourpackage_path, :notice => "Oops, Tour creation failed!"
      end
  end
   def edit
      @tourpackage = Tourpackage.find(params[:id])
    end

    def update
      if Tourpackage.find(params[:id]).update_attributes(params[:tourpackage])
          redirect_to root_path, :notice => "Success, Tour Package Updated!"
        else
          redirect_to new_tourpackage_path, :notice => "Oops, Tour updation failed!"
      end
    end

    def destroy
      Tourpackage.find(params[:id]).delete
      redirect_to root_path, :notice => "Success, Tour package Deleted"
    end
  end

app/controllers/travelagents_controller.rb
class TravelagentsController < ApplicationController
  def index
   @tours = current_travelagent.tourpackages.find_all_by_travelagent_id(@current_travelagent.id)
 end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tourpackages_helper.rb
module TourpackagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jumbo travel deal site</title>
  <%= stylesheet_link_tag    "application", "custom", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>	
		<div class="navbar">
			<div class="navbar-inner">
				<ul class="nav">
				<% if travelagent_signed_in? %>
					<li><%= link_to "Settings", "/travelagents" %></li>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Create new Packages", "/tourpackages/new" %></li>
			<li></li>  
			<li style= "float:right"><%= link_to " Signed in as #{current_travelagent.email} - Sign out", destroy_travelagent_session_path, :method => 'delete' %></li>
			<% else %>
			<li><%= link_to "Sign in ", new_travelagent_session_path %><li> <li><%= link_to "Sign Up", new_travelagent_registration_path %></li>
		<% end %>
		</ul>	
		</div>
		</div>
		</header>
		<div class="container">
			<% if flash[:notice] %>
			<div class='alert <% if flash[:notice] =~ /Success/i %> alert-success <% else %> alert-error<% end %>'>
			<p><%= flash[:notice] %></p>
			</div>
			<% end %>
				
				
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/tourpackages/create.html.erb
<h1>Tourpackages#create</h1>
<p>Find me in app/views/tourpackages/create.html.erb</p>

app/views/tourpackages/destroy.html.erb
<h1>Tourpackages#destroy</h1>
<p>Find me in app/views/tourpackages/destroy.html.erb</p>

app/views/tourpackages/edit.html.erb
<%= form_for @tourpackage do |f| -%>
<div class="field">
	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>
</div>  

<div class="field">
	<%= f.label :desc, "Description" %>
	<%= f.text_field :desc %>
</div>

<div class="field">
	<%= f.label :price, "Total Price" %>
	<%= f.text_field :price %>
</div>

<div class="field">
	<%= f.label :iternary, "Detailed Iternary" %>
	<%= f.text_area :iternary %> 
</div>

<div class="field">
	<%= f.label :numdays, "Number of days" %>
	<%= f.text_field :numdays %>
</div>

<div class="field">
	<%= f.label :countries, "Countries or Cities that will be covered" %>
	<%= f.text_field :countries %>
</div>

<div class="field">
	<%= f.label :landmarks, "Landmark places that the trip will cover" %>
	<%= f.text_field :landmarks %>
</div>

<div class="field">
	<%= f.label :sourcecity, "City from where the trip will start" %>
	<%= f.text_field :sourcecity %>
</div>

<div class="field">
	<%= f.label :sourceaddress, "Address of the departure point" %>
	<%= f.text_field :sourceaddress %>
</div>

<div class="field">
	<%= f.label :maxseats, "Maximum seats" %>
	<%= f.text_field :maxseats %>
</div>

<div class="field">
	<%= f.label :minseats, "Minimum number of people required to keep the deal on" %>
	<%= f.text_field :minseats %>
</div>

<div class="field">
	<%= f.label :incairfare, "Includes Airfare?" %>
	<%= f.radio_button :incairfare, :True %> 
	<%= f.radio_button :incairfare, :False %> 
</div>
<div class="field">
	<%= f.label :incbreakfast, "Includes breakfast?" %>
	<%= f.radio_button :incbreakfast, :True %> 
	<%= f.radio_button :incbreakfast, :False %> 
</div>
<div class="field">
	<%= f.label :inclunch, "Includes Lunch?" %>
	<%= f.radio_button :inclunch, :True %> 
	<%= f.radio_button :inclunch, :False %> 
</div>
<div class="field">
	<%= f.label :incsnacks, "Includes Snacks?" %>
	<%= f.radio_button :incsnacks, :True %> 
	<%= f.radio_button :incsnacks, :False %> 
</div>
<div class="field">
	<%= f.label :incdinner, "Includes Dinner?" %>
	<%= f.radio_button :incdinner, :True %> 
	<%= f.radio_button :incdinner, :False %> 
</div>
<div class="field">
	<%= f.label :active, "Active?" %>
	<%= f.radio_button :active, :True %> 
	<%= f.radio_button :active, :False %> 
</div>




<%= f.submit "Add", :disable_with => 'Adding...' %>
<% end -%>

app/views/tourpackages/index.html.erb
<h1>All the tour packages</h1>
<%if @tourpackage.count == 0 %>
	<p>No tour packages yet</p>
<% else %>
<table class="table table-striped table-bordered">
		<% if @tourpackage.count >0 %>
			<% @tourpackage.each do |t| %>
			<tr><td>
					<h1><%= link_to t.title, "/tourpackages/#{t.id}/show" %></h1>
					<p><%= t.desc %></p>
					<p><strong>Price: </strong><%= t.price %></p>
				</td></tr>
			<% end %>
		<% end %>	
<% end %>
</table>

app/views/tourpackages/new.html.erb
<%= form_for @tourpackage do |f| -%>
<div class="field">
	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>
</div>  

<div class="field">
	<%= f.label :desc, "Description" %>
	<%= f.text_field :desc %>
</div>

<div class="field">
	<%= f.label :price, "Total Price" %>
	<%= f.text_field :price %>
</div>

<div class="field">
	<%= f.label :iternary, "Detailed Iternary" %>
	<%= f.text_area :iternary %> 
</div>

<div class="field">
	<%= f.label :numdays, "Number of days" %>
	<%= f.text_field :numdays %>
</div>

<div class="field">
	<%= f.label :countries, "Countries or Cities that will be covered" %>
	<%= f.text_field :countries %>
</div>

<div class="field">
	<%= f.label :landmarks, "Landmark places that the trip will cover" %>
	<%= f.text_field :landmarks %>
</div>

<div class="field">
	<%= f.label :sourcecity, "City from where the trip will start" %>
	<%= f.text_field :sourcecity %>
</div>

<div class="field">
	<%= f.label :sourceaddress, "Address of the departure point" %>
	<%= f.text_field :sourceaddress %>
</div>

<div class="field">
	<%= f.label :maxseats, "Maximum seats" %>
	<%= f.text_field :maxseats %>
</div>

<div class="field">
	<%= f.label :minseats, "Minimum number of people required to keep the deal on" %>
	<%= f.text_field :minseats %>
</div>

<div class="field">
	<%= f.label :incairfare, "Includes Airfare?" %>
	<%= f.radio_button :incairfare, :True %> 
	<%= f.radio_button :incairfare, :False %> 
</div>
<div class="field">
	<%= f.label :incbreakfast, "Includes breakfast?" %>
	<%= f.radio_button :incbreakfast, :True %> 
	<%= f.radio_button :incbreakfast, :False %> 
</div>
<div class="field">
	<%= f.label :inclunch, "Includes Lunch?" %>
	<%= f.radio_button :inclunch, :True %> 
	<%= f.radio_button :inclunch, :False %> 
</div>
<div class="field">
	<%= f.label :incsnacks, "Includes Snacks?" %>
	<%= f.radio_button :incsnacks, :True %> 
	<%= f.radio_button :incsnacks, :False %> 
</div>
<div class="field">
	<%= f.label :incdinner, "Includes Dinner?" %>
	<%= f.radio_button :incdinner, :True %> 
	<%= f.radio_button :incdinner, :False %> 
</div>
<div class="field">
	<%= f.label :active, "Active?" %>
	<%= f.radio_button :active, :True %> 
	<%= f.radio_button :active, :False %> 
</div>




<%= f.submit "Add", :disable_with => 'Adding...' %>
<% end -%>

app/views/tourpackages/show.html.erb
<% if @tourpackage.blank? %>
	<h1>No tour package found</h1>
	
	<% else %>
	
	<div>
		<h1><%= @tourpackage.title %></h1>
		<p><%= @tourpackage.desc %></p>
		<p><%= @tourpackage.price %></p>
	</div>
	
	<% end %>
	

app/views/tourpackages/update.html.erb
<h1>Tourpackages#update</h1>
<p>Find me in app/views/tourpackages/update.html.erb</p>

app/views/travelagents/index.html.erb
<table class="table table-striped">
	<% @tours.each do |t| %>
<tr><td><%= t.title %></td>
	<td><%= link_to "Edit", "/tourpackages/#{t.id}/edit" %></td><td><%= link_to "Destroy", "/tourpackages/#{t.id}/" ,:method => 'DELETE' %></td></tr>
	<% end %>
</table>